project_name: inti

before:
  hooks:
    - go mod download

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'

release:
  disable: false

sboms:
-
  artifacts: archive

builds:
-
  id: cli
  dir: ./cmd/cli
  env: [CGO_ENABLED=0]
  ldflags: [-w -s -extldflags "-static"]
  goos: [darwin, linux, windows]
  goarch: [amd64, arm64]
  binary: inti

archives:
-
  format: zip
  name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
