name: lint

on: pull_request

jobs:
  golangci:
    name: go
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
    -
      name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: "--config=.github/golangci.yml"
